### ISSUE TITLE
macOS support 

### ISSUE THREAD

**Issue by mehdinourollah** [blackaleader/Discord-Proxy-Configuration-for-Proxifie#1]
Hey guys 
First thank you for this config and the effort
Do you have any idea how on macOS we can bypass the traffic ?

**Comment by blackaleader** [comment]
Hi there, and thanks for your message!

Since Proxifier is already available on macOS, I'm quite confident that the configuration can indeed have its macOS version. I would greatly appreciate it if you or any other macOS user could make a pull request for this. Thanks again!

**Comment by mehdinourollah** [comment]
Thanks for your quick response.
I thought since you were using platform Windows in your config file this is only for Windows platform.

Btw I found out another solution to this issue in another repo which I put here (feel free to close this issue since it's resolved IMO) 

https://gist.github.com/Colk-tech/157fd6c81032dde528d3a22434b8f3e6

I found that you can explicitly pass proxy server option to the application to run

**Comment by blackaleader** [comment]
Thank you for sharing the alternative solution and providing the gist .
